### ISSUE TITLE
Implement 'hint' button

### ISSUE THREAD

**Issue by simran-ss-sandhu** [dannyklaris/cloud-group-cw#1]
# Possible Requirements
- Provide a hint for each question
- Hint does not reveal the answer

# Possible Implementation
- Use Azure OpenAI API to generate the hints

**Comment by dannyklaris** [comment]
Completed this issue in commit 9da4af5. Unfortunately, we can't use Azure OpenAI due to restrictions. I'm thinking of making a scoring system where a user will be deducted scores when they click hint. That is for additional implementation of course. The basic functionality now works correctly and can be improved more later on.
